### ISSUE TITLE
How to Delete /snap in ROOT manually

### ISSUE THREAD

**Issue by AmberisMyShiba** [zigford/snapd#10]
I unmerged all snapd packages.But when I Can't delete /snap on ROOT,when I try to run rm -rf /snap.The system prompts that'/snap/core/10185/writable' cannot be deleted: read-only file system.Furthermore , I found some mount output like this /var/lib/snapd/snaps/core_10185.snap on /snap/core/10185 type squashfs (ro,nodev,relatime,x-gdu.hide)

How can I delete the /snap directory and is it safe?

**Comment by zigford** [comment]
You will need to unmount all snaps first.
Something like: 
```
sudo umount /var/lib/snapd/snaps/*.snap
```

**Comment by AmberisMyShiba** [comment]
> You will need to unmount all snaps first.
> Something like:
> 
> ```
> sudo umount /var/lib/snapd/snaps/*.snap
> ```

thanks . I resolved it
