### ISSUE TITLE
Incorrect DEPEND, use BDEPEND instead

### ISSUE THREAD

**Issue by vilgotf** [zigford/snapd#5]
`>=dev-lang/go-1.9` (and others although I haven't looked into those) should be under `BDEPEND` instead of under `DEPEND`.
`BDEPEND` is for build time dependencies i.e. packages needed for building and having it only exist under `BDEPEND` means that binaries do not needlessly depend on build-time packages.

**Comment by zigford** [comment]
I'm version bumping to 2.43.3 in the dev branch and will switch it to BDEPEND there.

**Comment by zigford** [comment]
I'll try new version on my machines for a couple of days before merging to master

**Comment by vilgotf** [comment]
I would guess that `dev-python/docutils` is also only for building (dodoc?) and also why is `sys-fs/xfsprogs` required? Seems a bit weird considering it isn't a requirement for other distributions.

**Comment by zigford** [comment]
I'm getting around to testing your suggestions in a VM. I forked this ebuild from [JamesB192](https://github.com/JamesB192/JamesB192-overlay/tree/master/app-emulation/snapd) and it already had xfsprogs in it. 

Looking at the [source package from ubuntu](https://packages.ubuntu.com/source/xenial/snapd) does reference xfslibs-dev so perhaps there is some requirement? 

Anyhow, I'll try build it without and see.

**Comment by zigford** [comment]
Looks like if def needs xfs:

    checking for xfs/xqm.h... no
    configure: error: xfs/xqm.h unavailable
I'll see how it goes as a build dep

**Comment by zigford** [comment]
docutils is required for the man pages, so I've split it out to a `man` use flag. Added a `doc` use flag too, but that's just some release notes and changelog.  Let me know if you think that'l do the trick

**Comment by vilgotf** [comment]
Awesome!
