### ISSUE TITLE
Temporary Directory Cannot be Created

### ISSUE THREAD

**Issue by ghost** [zigford/snapd#6]
I've done everything I can think of to make this work.  Snap is active, and applications install like a dream.  However, when I attempt to run those snap-installed programs, I get the following error message, and the program won't run (even with sudo): 

`cannot create temporary directory for the root file system: Permission denied`

This has happened when I attempted to install and run the "hello-world" program, as well as attempts with Blender and Paint Supreme 3D.

I use systemd, and from what I can tell, all the recommended snap systems are running (snapd.apparmor.service, snapd.service, snapd.socket, run-snapd-ns.mount, and all snap-(application)-####.mount services).

I've included systemd and apparmor logs, as well as a debug log of the attempt to run "hello-world."

[apparmor.log](https://github.com/zigford/snapd/files/4397624/apparmor.log)
[systemd.log](https://github.com/zigford/snapd/files/4397625/systemd.log)
[hello-world.log](https://github.com/zigford/snapd/files/4397637/hello-world.log)

Is this something I'm missing on my end?

**Comment by zigford** [comment]
Can you post the output of `snap debug confinement` and `snap debug sandbox-features`

**Comment by zigford** [comment]
I see `snapd.apparmor.service` is not started. Can you try enable and start it with `systemctl enable --now snapd.apparmor.service`

**Comment by ghost** [comment]
Nothing changes; same error message.  I tried to start the service using systemctl a few times, but it remains in "exited" status, and the results are the same.  Here's the status of that specific service:
```
$ sudo systemctl status snapd.apparmor.service
● snapd.apparmor.service - Load AppArmor profiles managed internally by snapd
     Loaded: loaded (/lib/systemd/system/snapd.apparmor.service; enabled; vendor preset: disabled)
     Active: active (exited) since Sun 2020-03-29 23:48:31 EDT; 6h ago
   Main PID: 2373 (code=exited, status=0/SUCCESS)
     Memory: 0B
     CGroup: /system.slice/snapd.apparmor.service

Mar 29 23:48:30 atlon systemd[1]: Starting Load AppArmor profiles managed internally by snapd...
Mar 29 23:48:31 atlon systemd[1]: Started Load AppArmor profiles managed internally by snapd.
```

Here are the other outputs you requested:

```
$ snap debug confinement
partial
```

```
apparmor:             kernel:caps kernel:domain kernel:file kernel:mount kernel:namespaces kernel:network_v8 kernel:policy kernel:ptrace kernel:query kernel:rlimit kernel:signal parser:unsafe policy:downgraded support-level:partial
confinement-options:  classic devmode
dbus:                 mediated-bus-access
kmod:                 mediated-modprobe
mount:                freezer-cgroup-v1 layouts mount-namespace per-snap-persistency per-snap-profiles per-snap-updates per-snap-user-profiles stale-base-invalidation
seccomp:              bpf-actlog bpf-argument-filtering kernel:allow kernel:errno kernel:kill_process kernel:kill_thread kernel:log kernel:trace kernel:trap
udev:                 device-cgroup-v1 device-filtering tagging
```

**Comment by zigford** [comment]
Everything looks right. Can you try remove all snaps and then re-install and try again from fresh? I've had a few issues in the past that were fixed like this.
Cleanup
```
    systemctl stop snapd
    if [[ -d /snap ]]; then
	    for i in /snap/*; do
	        if [[ -d "${i}" ]]; then
		        if mount | grep -q "${i}"; then
			        umount "${i}/current"
			    fi
		    fi
	    cd /
		rm -rf snap
    fi 
```

**Comment by ghost** [comment]
Same result.  I also tried cleaning everything snapd off the system, uninstalling the main program, deleting the /snap directory, the /var/snap directory, all the systemd scripts for snap, rebooting, and then reinstalling snap and then hello-world again.  The same error message occurs.

**Comment by zigford** [comment]
I'm digging a little in the snapd source to see what could be going wrong. The error seems to be generated from this line in [snap-confine](https://github.com/snapcore/snapd/blob/5ac5359d3b4bbab5b1a4d942d03a5fa7856a997e/cmd/snap-confine/mount-support.c#L228)
Which is trying to make a directory in /tmp. Is there anything funky about /tmp on your system? What happens if you `mkdir /tmp/blah` ?

**Comment by zigford** [comment]
My tmp looks like this: 
```
mount | grep /tmp
tmpfs on /tmp type tmpfs (rw,nosuid,nodev)
```

**Comment by ghost** [comment]
Hmmm... that's a good question.

The `/temp` directory contains a separate partition, holding two directories: `/temp/root` and `/temp/var`.  `/tmp` is symlinked to `/temp/root`, while `/var/tmp` is linked to `/temp/var`.  This is to ensure that both temporary directories would share the same 164GB of space, separate from the `/var` and `/` partitions, while not doing anything funky to system RAM.

So the question is, would snap have a problem if /tmp is a symlink, and not a directory?

By the way, here is the `ls -la /temp` command, to give you an idea of permissions:

$ ls -l /temp
total 56
drwx------  2 root root 16384 Nov  1 22:42 lost+found
drwxrwxrwt 92 root root 32768 Apr 12 16:10 root
drwxrwxrwt 34 root root  4096 Apr 11 21:27 var

**Comment by zigford** [comment]
I tried this myself in my own recreation of your environment and it worked. But to be 100% sure, compile and run this snippet of C to test:
```
#include <stdio.h>
#include <stdlib.h>

int main() {
    char scratch[] = "/tmp/hello_XXXXXX";
    if (mkdtemp(scratch) == NULL) {
        printf("It didn't work");
    } else {
        printf("Dir is: %s", scratch);
    }
}
```

**Comment by ghost** [comment]
Okay, done.  I added "\n" to the printf lines so that the command prompt wouldn't append itself to the end of the output.

```
$ gcc test.c
$ ./a.out 
Dir is: /tmp/hello_EWEXBR
$ ./a.out
Dir is: /tmp/hello_3kvP8F
$
```

**Comment by zigford** [comment]
It just hit me, apparmor doesn't like symlinks. You will need to adjust `/etc/apparmor.d/usr.lib.snapd.snap-confine.real` and swap out any instances of `/tmp/snap` with `/temp/root/snap`.

Perhaps something like this: 

```
cp /etc/apparmor.d/usr.lib.snapd.snap-confine.real{,.bak}
sed -ie 's|tmp/|temp/root/|g' /etc/apparmor.d/usr.lib.snapd.snap-confine.real
apparmor_parser -r /etc/apparmor.d/usr.lib.snapd.snap-confine.real
```
That will give snap-confine permission to create the tmp dir in confinement

**Comment by reteo** [comment]
Well, the issue has changed at this point:  instead of the previous error message, it now states the following:

```
$ hello-world
cannot perform operation: mount --bind /tmp/snap.rootfs_Iskta5 /tmp/snap.rootfs_Iskta5: Permission denied
```

Perhaps apparmor takes note of the literal path, rather than the logical location of the file/directory?

**Comment by ghost** [comment]
Okay, I've edited `/etc/apparmor.d/usr.lib.snapd.snap-confine.real` using vim with the command:
```
:%s/tmp\//temp\/root\//g
```
Now, the error has changed to the following:
```
$ hello-world
cannot perform operation: mount --rbind /tmp /tmp/snap.rootfs_kBEqIU//tmp: Permission denied
```
Perhaps apparmor also takes paths literally, instead of looking at the logical location of a specific path?

**Comment by zigford** [comment]
I used aa-logprof to generate a working apparmor profile for you. 

https://gist.github.com/zigford/0c6e96cf2d40584d6c62c460eca921db

**Comment by zigford** [comment]
There could be other changes needed to support an odd tmp setup and I'll leave that to you

**Comment by ghost** [comment]
It's still not working ("line 1: syntax error, unexpected TOK_ID, expecting TOK_OPEN"), even after fixing the missing comment symbol on the first line.  However, I suspect it just means I need to spend some time getting familiar with systemd (I'm not a fan of it, but I've seen the writing on the wall).  Thanks for the help, however!

**Comment by ezra100** [comment]
Hi
I ran into a similar issue with a symlinked /tmp directory, I solved it with replacing the symlink with a bind-mount at startup.
I just created an empty `/tmp` folder and added the following line at the end of `/etc/fstab`

`
/temp/root     /tmp    none     defaults,bind     0    0
`
Hope this helps
